### PR TITLE
Check if error message contains internal server error

### PR DESCRIPTION
**Pull request by dextermb**
- If error message contains "internal server error" then attempt to set the status code of at least `500`

### CODE REVIEW

**Comment by DivineOmega** [comment]
I'm not sure I understand the use case for this.

Surely if you are setting the error message manually to 'Internal Server Error', you'd also set the status?

**Comment by dextermb** [comment]
> I'm not sure I understand the use case for this.
> 
> Surely if you are setting the error message manually to 'Internal Server Error', you'd also set the status?

It's just a way of making sure that actual server errors are `500` statuses, currently in the example below it'll just return `400` (which is default) but what if creating an address fails because of a server error?

```php
#...

class AddressController extends Controller
{
    # ...

    /**
     * @param CreateAddressRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function create(CreateAddressRequest $request)
    {
        try {
            $address = Address::create($request->validated());

            return ApiResponse::success(compact('address'))->status(201)->json();
        } catch (\Exception $e) {
            return ApiResponse::error($e->getMessage())->json();
        }
    }

    # ...
}

**Comment by DivineOmega** [comment]
That makes sense then. It might be useful to make it so if a status is manually specified it will override this automatic detection.

**Comment by dextermb** [comment]
> That makes sense then. It might be useful to make it so if a status is manually specified it will override this automatic detection.

@DivineOmega It checks to see if you are already giving a 500+ status code, or sets it to 500.

Wouldn't get overwritten:
```
ApiResponse::error('Internal server error', 504)->json();
```
```
ApiResponse::error('Internal server error')->status(504)->json();
```

Will get overwritten (set to 500):
```
ApiResponse::error('Internal server error', 200)->json();
```
```
ApiResponse::error('Internal server error')->status(200)->json();
```

**Comment by dextermb** [comment]
cc @DivineOmega @robmilward @wheatleyjj

**Pull request closed without merging**
